### ISSUE TITLE
Odd styling issue

### ISSUE THREAD

**Issue by xerosis** [iphands/Meltdown#15]
Firstly, amazing software. I've been looking everywhere for something that wasn't terrible and this has surpassed it! I'm sure it's something I've done wrong but the styling is a bit off for me in both Chrome and Firefox, see below:
![screen shot 2015-04-16 at 13 47 01](https://cloud.githubusercontent.com/assets/1820754/7178366/48cba780-e43f-11e4-831d-e5551af9215c.png)

**Comment by xerosis** [comment]
Guess it'd help if I had the fonts...

**Comment by xerosis** [comment]
Hm, even after adding the fonts and using an older version of the CSS from the demo I still get this:
![screen shot 2015-04-16 at 16 35 43](https://cloud.githubusercontent.com/assets/1820754/7180889/cfb695e0-e456-11e4-80f6-27dc8b79eb38.png)

**Comment by xerosis** [comment]
Okay it seems there's a conflict with bootstrap

**Comment by wodCZ** [comment]
I also have this issue ![](http://i.imgur.com/dXj8hx2.png)

I'm using [SB Admin 2](http://startbootstrap.com/template-overviews/sb-admin-2/) (Bootstrap 3)

Don't you have any temp fix, @xerosis?

**Comment by wodCZ** [comment]
OK, I've added this in styles:

```css
	<style>
		.meltdown_wrap, .meltdown_wrap * {
			-webkit-box-sizing: content-box;
			-moz-box-sizing: content-box;
			box-sizing: content-box;
		}
	</style>
```

Now it works as expected.
